######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 30 11:44:30 2010
######################################################################

TEMPLATE = app
TARGET = ../tsp
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += config.h mapWidget.h tsp_evolution.h workSpace.h
SOURCES += config.cc main.cc mapWidget.cc tsp_evolution.cc workSpace.cc
